---
version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server2/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:8080'
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "8081:3000"
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=kingyo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
volumes:
  db-store:
