---
version: '3.6'
services:
  server:
    image: ghcr.io/hokita/kingyo_server:latest
      # build:
      #   context: .
      #   dockerfile: ./docker/server/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:9000'
  front:
    image: ghcr.io/hokita/kingyo_front:latest
      # build:
      #   context: .
      #   dockerfile: ./docker/front/Dockerfile
    ports:
      - "8081:3000"
  db:
    image: ghcr.io/hokita/kingyo_db:latest
      # build:
      #   context: .
      #   dockerfile: ./docker/db/Dockerfile
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=kingyo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
volumes:
  db-store:
