---
version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    ports:
      - '8080:8080'
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    ports:
      - "8081:3000"
