---
version: '3.6'
services:
  server:
    build:
      context: .
      dockerfile: ./docker/server/Dockerfile
    depends_on:
      - db
    ports:
      - '8080:9000'
    command: [ "java","-jar","/server/server.jar" ]
  front:
    build:
      context: .
      dockerfile: ./docker/front/Dockerfile
    volumes:
      - ./front:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8081:3000"
    command: sh -c "yarn start"
  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    platform: linux/amd64
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=kingyo
      - MYSQL_USER=sa
      - MYSQL_PASSWORD=1234
    volumes:
      - db-store:/var/lib/mysql
      - ./logs:/var/log/mysql
volumes:
  db-store:
